final Map<String, List<String>> interestItems = {
  "Fashion & beauty": [
    "Fashon Show",
    "Woman suit",
    "Skirt",
    "Woman pants",
    "Fasion Designer",
    "Celebrator"
  ],
  "Outdoors": [],
  "Arts & culture": [],
  "Animation & comics": [
    "Anime",
    "Movies & TV",
    "Harry Potter",
    "Mavel Universe",
    "Movie news",
    "Movies",
    "Actor",
    "Actress",
    "Golden awards"
  ],
  "Business & finance": [],
  "Food": [],
  "Travel": [],
  "Entertainment": [],
  "Music": [
    "Rap",
    "R&B & soul",
    "Grammy Awards",
    "Pop",
    "K-pop",
    "Music industry",
    "Music news",
    "Hip hop",
    "Reggae",
    "Trot"
  ],
  "Gaming": [
    "Blizard",
    "Nexon",
    "Valorant",
    "Lol",
    "Startcraft",
    "Bang bang car",
    "Bubble bubble",
    "Galaxy",
    "Invader",
    "Gaming industry",
    "Hacker"
  ],
  "Camping": [
    "Tent",
    "Tarp",
    "Table",
    "Chair",
    "Helinox",
    "Herzen",
    "Backpacking",
    "Bibak",
    "Solo camping",
    "bushe craft",
    "Gas accident"
  ],
  "Driving": ["I", "want", "to", "driving", "with", "my", "dream", "car"],
  "Diving": ["I", "cant", "to", "diving", "it's", "so", "scare"],
  "Swimming": [],
  "Fighting": ["I", "don't", "want", "to", "fighting", "...", "Peace!!!!!"],
  "Sleeping": [],
};
